feat: add additional input to define how to fail the action
dawidd6/action-download-artifact pull request #187
Opened 2022-08-19 14:23 UTC by jaypea

this adds an additional input `if_no_files_found` which follows the semantic of `upload-artifact`.

the proposes solution in the issue comments to use `continue-on-error` has the ugly side-effect of showing a red warning in the workflow summary.
as I'm trying to train the developers to actually look at this summary in order to watch out for lint warning, they should now see red false-negative results in this list.

2022-08-19 16:29 UTC, dawidd6 requested changes

2022-08-19 16:29 UTC, dawidd6 commented on main.js
> +            return;
Please don't add semicolons

2022-08-19 16:29 UTC, dawidd6 commented on action.yml
> +  if_no_files_found: false
Syntax error here

2022-08-19 16:29 UTC, dawidd6 commented on README.md
> +    if_no_files_found: false
Maybe if_no_artifact_found would be better?

2022-08-21 11:16 UTC, jaypea commented on README.md
> +    if_no_files_found: false
I wanted to use the same name as in upload-artifact action.
I think you're right, its about artifacts, so it should be reflected in the name.

2022-08-29 17:20 UTC, dawidd6 commented on README.md
> +    if_no_artifact_found: false
Yep

2022-08-29 17:22 UTC, dawidd6 commented on README.md
> +    if_no_artifact_found: false
Actually I'm not sure if IGNORE should be the default. Current behavior is to exit with error if no artifacts are found, am I right?

2022-08-29 17:37 UTC, benkane commented on README.md
> +    if_no_artifact_found: false
Correct. So fail is probably the correct default to be backwards compatible while adding the feature to warn or ignore

2022-08-29 17:40 UTC, benkane commented on README.md
> +    if_no_artifact_found: false
On the other hand, the upload-artifact default for `if-no-files-found` is to warn. Depends on if @jaypea wants to lean into match those semantics or not. Personally I would keep error as the default so as not to introduce a breaking change

2022-08-30 09:07 UTC, jaypea commented on README.md
> +    if_no_artifact_found: false
yes, I wanted to follow the upload-artifact semantics. 
Though I agree its better to not introduce a breaking change in this package, so the default is now "fail"

2022-08-30 09:49 UTC, dawidd6 commented on action.yml
> +    default: "fail"
```suggestion
    default: fail
```

2022-08-30 09:49 UTC, dawidd6 commented on action.yml
> +    description: Boolean output which is true if the artifact was found and false otherwise.
Those 2 outputs are doing exactly the same thing in case dry_run is requested. Not blocking this PR, just thinking loud maybe the dry_run output should go away with v3 release.

2022-08-30 09:49 UTC, dawidd6 commented on main.js
> +            return
```suggestion
            return exitWithMessage(ifNoArtifactFound, "no matching workflow run found with any artifacts?")
```

Could we do it like this?

2022-08-30 09:49 UTC, dawidd6 commented on main.js
> +
```suggestion
```

2022-08-30 09:50 UTC, dawidd6 commented
Imma go ahead and merge this, will do some adjustments later. Thanks!

2022-08-30 09:50 UTC, merged